name: Docker Build, Scan and Compose Test

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Push to Docker Hub
        if: success()
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

  test-compose:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Deploy Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 25

      - name: Test Create endpoint
        run: |
          curl -X POST http://localhost:8080/crear \
            -H "Content-Type: application/json" \
            -d '{"nombre":"Test","telefono":"123","direccion":"Test","cedula":"999","correo":"test@correo.com"}'

      - name: Test Read endpoint
        run: curl --fail http://localhost:8082/hola || exit 1

      - name: Clean up Docker Compose
        if: always()
        run: docker-compose down -v
