name: Docker CI/CD with Release

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # Detecta versiones como v1.0.0, v2.3.1, etc.

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.ref_name }} .

      - name: Install Trivy and scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.ref_name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Push Docker image
        if: success()
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.ref_name }}

  test-endpoints:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run Read service (GET /hola)
        run: |
          docker run -d -p 8082:8080 --name hola-golang ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.ref_name }}
          sleep 15

      - name: Test Read endpoint
        run: curl --fail http://localhost:8082/hola || exit 1

      - name: Docker Compose up all services
        run: |
          docker-compose -f ./docker-compose.yaml up -d
          sleep 15

      - name: Test Create endpoint
        run: |
          curl -X POST http://localhost:8080/create \
            -H "Content-Type: application/json" \
            -d '{"nombre":"Test","telefono":"123","direccion":"Test","cedula":"999","correo":"test@correo.com"}' \
            || exit 1

  unit-tests:
    needs: test-endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Restore Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test create-service
        working-directory: ./create
        run: go test ./controllers -v --cover

      - name: Test read-service
        working-directory: ./read
        run: go test ./controllers -v --cover

      - name: Test update-service
        working-directory: ./update
        run: go test ./controllers -v --cover

      - name: Test delete-service
        working-directory: ./delete
        run: go test ./controllers -v --cover

  release:
    needs: unit-tests
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🚀 Nuevo release automático generado por CI/CD
            - Imagen Docker: `${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.ref_name }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
