name: Docker Build and Scan

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest .

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Push to Docker Hub
        if: success()  # Solo si pasa Trivy
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest

  test-container-image_1:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker image
        run: |
          docker run -d -p 3000:8080 --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
          sleep 15  # Esperar que arranque

      - name: Test endpoint
        run: |
          curl --fail http://localhost:3000/hola || exit 1

      - name: Clean up container
        if: always()
        run: docker rm -f test-container

test-container-compose:
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Docker image
        run: |
          docker-compose -f docker-compose.yml up -d  # Levanta los servicios con Docker Compose
          sleep 15  # Esperar que arranquen los servicios

      - name: Test Create endpoint (POST)
        run: |
          curl -X POST http://localhost:8080/create \
            -H "Content-Type: application/json" \
            -d '{"nombre":"Test","telefono":"123","direccion":"Test","cedula":"999","correo":"test@correo.com"}' \
            || exit 1

      